#version 450

layout (local_size_x = 128, local_size_y = 1, local_size_z = 1) in;

layout (binding = 0, set = 0) buffer InputBuffer0 {
    int inArray1[];
};
layout (binding = 1, set = 0) buffer InputBuffer1 {
    int inArray2[];
};
layout (binding = 0, set = 1) buffer OutputBuffer0 {
    int outArray1[];
};
layout (binding = 1, set = 1) buffer OutputBuffer1 {
    int outArray2[];
};

void main(void){
    uint index = gl_GlobalInvocationID.x;
    outArray1[index] = inArray1[index];
    outArray2[index] = inArray2[index];
}
